title:            Nefeli Kostakopoulou | Νεφέλη Κωστακοπούλου
description:      This is the personal blog of Nefeli Kostakopoulou. Thoughts and posts about STEM and Education...
url:              https://nefeli.dev
permalink:        pretty
timezone:         Europe/Athens
sass:
  sass_dir: assets
  style: :compressed
collections:
  - notes
