title:            nefeli
description:      who is nefeli
url:              https://nefeli.dev
permalink:        pretty
timezone:         America/New_York
sass:
  sass_dir: assets
  style: :compressed
collections:
  - notes
